/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.82
 * Generated at: 2018-03-05 18:02:37 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import org.apache.juddi.config.Property;
import org.apache.juddi.config.AppConfig;
import org.apache.juddi.api_v3.Publisher;
import org.apache.juddi.api_v3.SavePublisher;
import org.apache.juddi.api_v3.Clerk;
import org.apache.juddi.api_v3.SaveClerk;
import org.apache.juddi.api_v3.SyncSubscription;
import org.apache.juddi.api_v3.GetPublisherDetail;
import org.apache.juddi.api_v3.GetAllPublisherDetail;
import org.apache.juddi.api_v3.DeletePublisher;
import org.uddi.api_v3.DeleteTModel;
import org.apache.juddi.v3_service.JUDDIApiPortType;
import org.apache.commons.lang.StringEscapeUtils;
import org.apache.juddi.adminconsole.hub.UddiAdminHub;
import org.apache.juddi.adminconsole.resources.ResourceLoader;
import org.apache.juddi.adminconsole.hub.UddiAdminHub;
import org.apache.juddi.adminconsole.CrossSiteRequestForgeryException;
import org.apache.juddi.adminconsole.hub.UddiAdminHub;
import org.apache.juddi.adminconsole.resources.ResourceLoader;
import org.apache.commons.lang.StringEscapeUtils;
import org.apache.commons.lang.StringEscapeUtils;
import java.io.IOException;
import java.util.jar.Attributes;
import java.util.jar.Manifest;
import java.io.InputStream;
import java.util.jar.JarFile;
import java.net.URL;
import java.util.Enumeration;
import org.apache.juddi.adminconsole.resources.ResourceLoader;

public final class admin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/admin/csrf.jsp", Long.valueOf(1477445500000L));
    _jspx_dependants.put("/admin/header-top.jsp", Long.valueOf(1477445500000L));
    _jspx_dependants.put("/admin/login.jsp", Long.valueOf(1477445500000L));
    _jspx_dependants.put("/admin/header-bottom.jsp", Long.valueOf(1477445500000L));
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");

    //this is to catch someone that bookmarked a page after selecting a language
    Cookie[] cookies2 = request.getCookies();
    if (cookies2 != null && cookies2.length > 0) {
        for (int i = 0; i < cookies2.length; i++) {
            if (cookies2[i] != null && cookies2[i].getName() != null && cookies2[i].getName().equalsIgnoreCase("locale")) {
                if (cookies2[i].getValue() != null) {
                    session.setAttribute("locale", cookies2[i].getValue());
                }
            }
        }
    }
    if (session.getAttribute("locale") == null) {
        //last chance, default to english
        session.setAttribute("locale", "en");
    }

      out.write("\r\n");
      out.write("<html lang=\"");
      out.print((String) session.getAttribute("locale"));
      out.write("\" dir=\"");
      out.print(ResourceLoader.GetResource(session, "direction"));
      out.write("\">\r\n");
      out.write("    <head>\r\n");
      out.write("        <meta charset=\"utf-8\">\r\n");
      out.write("        <title>");
      out.print(ResourceLoader.GetResource(session, "title"));
      out.write("</title>\r\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("        <meta name=\"description\" content=\"");
      out.print(ResourceLoader.GetResource(session, "description"));
      out.write("\">\r\n");
      out.write("        <meta name=\"author\" content=\"Apache Software Foundation\">\r\n");
      out.write("\r\n");
      out.write("        <link href=\"css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("        <link href=\"css/bootstrap-datetimepicker.min.css\" rel=\"stylesheet\">\r\n");
      out.write("        <link href=\"css/bootstrap-timepicker.min.css\" rel=\"stylesheet\">\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"css/font-awesome.min.css\">\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"css/ui-lightness/jquery-ui-1.10.2.custom.min.css\">\r\n");
      out.write("        <!--[if IE 7]>\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"css/font-awesome-ie7.min.css\">\r\n");
      out.write("        <![endif]-->\r\n");
      out.write("\r\n");
      out.write("        <link rel=\"shortcut icon\" href=\"favicon.ico\" />\r\n");
      out.write("        <style type=\"text/css\">\r\n");
      out.write("            body {\r\n");
      out.write("                padding-top: 60px;\r\n");
      out.write("                padding-bottom: 40px;\r\n");
      out.write("            }\r\n");
      out.write("        </style>\r\n");
      out.write("        <link href=\"css/bootstrap-responsive.min.css\" rel=\"stylesheet\">\r\n");
      out.write("        <link href=\"css/bootstrap-modal.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("        <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->\r\n");
      out.write("        <!--[if lt IE 9]>\r\n");
      out.write("          <script src=\"js/html5shiv.js\"></script>\r\n");
      out.write("        <![endif]-->\r\n");
      out.write("\r\n");
      out.write("        <!-- Fav and touch icons -->\r\n");
      out.write("\r\n");
      out.write("        <link rel=\"shortcut icon\" href=\"ico/favicon.png\">\r\n");
      out.write("        <script src=\"js/jquery-1.9.1.js\"></script>\r\n");
      out.write("        <script src=\"js/i18n.js.jsp\"></script>\r\n");
      out.write("        <script src=\"js/bootstrap.min.js\"></script>\r\n");
      out.write("        <script src=\"js/bootstrap-datetimepicker.min.js\"></script>\r\n");
      out.write("        <script src=\"js/bootstrap-timepicker.min.js\"></script>\r\n");
      out.write("        <script src=\"js/bootstrap-modalmanager.js\"></script>\r\n");
      out.write("        <script src=\"js/bootstrap-modal.js\"></script>\r\n");
      out.write("        <script src=\"js/jquery.jeditable.js\"></script>\r\n");
      out.write("        <script src=\"js/jquery-ui-1.10.2.custom.min.js\"></script>\r\n");
      out.write("        <script src=\"js/main.js\"></script>\r\n");
      out.write("    </head>\r\n");
      out.write("\r\n");
      out.write("    <body>\r\n");
      out.write("        <form id=\"uddiform\">\r\n");
      out.write("            ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

    //this is to catch someone that bookmarked a page after selecting a language
    Cookie[] cookies3 = request.getCookies();
    if (cookies3 != null && cookies3.length > 0) {
        for (int i = 0; i < cookies3.length; i++) {
            if (cookies3[i] != null && cookies3[i].getName() != null && cookies3[i].getName().equalsIgnoreCase("locale")) {
                if (cookies3[i].getValue() != null) {
                    session.setAttribute("locale", cookies3[i].getValue());
                }
            }
        }
    }
    if (session.getAttribute("locale")==null){
        //last change, default to english
        session.setAttribute("locale", "en");
    }
    String currentNonce = null;

    if (request.getMethod().equalsIgnoreCase("post")) {

        if ((request.getParameter("nonce") == null || request.getParameter("nonce").isEmpty())) {
            //reject it
            session.removeAttribute("nonce");
            response.sendRedirect("index.jsp");
            UddiAdminHub.log.warn( "CSRF Test failed, no nonce guid." + request.getRemoteAddr() + request.getRemoteUser());
            //throw new CrossSiteRequestForgeryException();
            response.sendRedirect("index.jsp");
                
                return;
        } else {

            String noncestr = (String) session.getAttribute("nonce");
            if (noncestr == null) {
                //no session variable to test against, reject it
                UddiAdminHub.log.warn( "CSRF Test failed, no session guid." + request.getRemoteAddr() + request.getRemoteUser());
                session.removeAttribute("nonce");
                //throw new CrossSiteRequestForgeryException("Cross Site Request Forgery");
                response.sendRedirect("index.jsp");
                
                return;
            }
            String postedstr = request.getParameter("nonce");

            //check session against existing nonce, if match
            //generate new one, add to page and session
            //else redirect to index page
            if (noncestr.equals(postedstr)) {
                currentNonce = noncestr;
                //OK
                // current = UUID.randomUUID();
                //session.removeAttribute("nonce");
                // session.setAttribute("nonce", current.toString());
                UddiAdminHub.log.info( "CSRF Test passed.");
            } else {
                //mismatch, reject it
                UddiAdminHub.log.warn( "CSRF Test failed, session did not match nonce guid." + request.getRemoteAddr() + request.getRemoteUser());
                session.removeAttribute("nonce");
                //throw new CrossSiteRequestForgeryException("Cross Site Request Forgery");
                response.sendRedirect("index.jsp");
                
                return;
            }
        }
    } else {
        //HTTP GET or otherwise message
        if ((currentNonce == null) || currentNonce.isEmpty()) {
            currentNonce = (String)session.getAttribute("nonce");
            if (currentNonce == null) {
                currentNonce = java.util.UUID.randomUUID().toString();
            }
            session.setAttribute("nonce", currentNonce);
        }

    }


      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("            <input type=\"hidden\" name=\"nonce\" id=\"nonce\" value=\"");
      out.print(StringEscapeUtils.escapeHtml((String) session.getAttribute("nonce")));
      out.write("\" />\r\n");
      out.write("            <div class=\"alert\" style=\"display:none; position: fixed; top:45px; width:80%; left: 10%; z-index: 1000; opacity: 1.0; background-color: #FFD530; color:black \" id=\"resultBar\">\r\n");
      out.write("            </div>\r\n");
      out.write("            ");

                UddiAdminHub hub = UddiAdminHub.getInstance(application, session);
            
      out.write("\r\n");
      out.write("\r\n");
      out.write("            <div class=\"navbar navbar-inverse navbar-fixed-top\">\r\n");
      out.write("                <div class=\"navbar-inner\">\r\n");
      out.write("                    <div class=\"container\">\r\n");
      out.write("                        <button type=\"button\" class=\"btn btn-navbar\" data-toggle=\"collapse\" data-target=\".nav-collapse\">\r\n");
      out.write("                            <span class=\"icon-bar\"></span>\r\n");
      out.write("                            <span class=\"icon-bar\"></span>\r\n");
      out.write("                            <span class=\"icon-bar\"></span>\r\n");
      out.write("                        </button>\r\n");
      out.write("                        <a class=\"brand\" href=\"home.jsp\" style=\"padding-left:19px; padding-top:0px; padding-bottom:0px\"><img src=\"img/logo2.png\"></a>\r\n");
      out.write("                        <div class=\"nav-collapse collapse\">\r\n");
      out.write("                            <ul class=\"nav\">\r\n");
      out.write("                                <li><a href=\"home.jsp\" ><i class=\"icon-home icon-large\"></i> ");
      out.print(ResourceLoader.GetResource(session, "navbar.home"));
      out.write("</a></li>\r\n");
      out.write("                                <li><a href=\"stats.jsp\" ><i class=\"icon-camera icon-large\"></i> Status");
//=ResourceLoader.GetResource(session, "navbar.home")
      out.write("</a></li>\r\n");
      out.write("                                <li><a href=\"configure.jsp\" ><i class=\"icon-cog icon-large\"></i> Configure");
//=ResourceLoader.GetResource(session, "navbar.home")
      out.write("</a></li>\r\n");
      out.write("                                <li><a href=\"admin.jsp\" ><i class=\"icon-cogs icon-large\"></i> Admin");
//=ResourceLoader.GetResource(session, "navbar.home")
      out.write("</a></li>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                                <li class=\"dropdown\"><a href=\"#\" data-toggle=\"dropdown\" class=\"dropdowb-town\"><i class=\"icon-question-sign icon-large\"></i>");
      out.print(ResourceLoader.GetResource(session, "navbar.help"));
      out.write(" <b class=\"caret\"></b></a>\r\n");
      out.write("                                    <ul class=\"dropdown-menu\">\r\n");
      out.write("                                         <li><a href=\"http://juddi.apache.org/docs.html\" title=\"");
      out.print(ResourceLoader.GetResource(session, "navbar.help.userguide"));
      out.write('"');
      out.write('>');
      out.print(ResourceLoader.GetResource(session, "navbar.help.userguide"));
      out.write("</a></li>\r\n");
      out.write("                                        <li><a href=\"http://wiki.apache.org/juddi\" title=\"");
      out.print(ResourceLoader.GetResource(session, "navbar.help.wiki"));
      out.write('"');
      out.write('>');
      out.print(ResourceLoader.GetResource(session, "navbar.help.wiki"));
      out.write("</a></li>\r\n");
      out.write("                                        <li><a href=\"http://juddi.apache.org/issue-tracking.html\" title=\"");
      out.print(ResourceLoader.GetResource(session, "navbar.help.bugreport"));
      out.write('"');
      out.write('>');
      out.print(ResourceLoader.GetResource(session, "navbar.help.bugreport"));
      out.write("</a></li>\r\n");
      out.write("                                        <li><a href=\"http://juddi.apache.org/\" title=\"");
      out.print(ResourceLoader.GetResource(session, "navbar.help.website"));
      out.write('"');
      out.write('>');
      out.print(ResourceLoader.GetResource(session, "navbar.help.website"));
      out.write("</a></li>\r\n");
      out.write("                                        <li><a href=\"http://juddi.apache.org/mailing-list.html\" title=\"");
      out.print(ResourceLoader.GetResource(session, "navbar.help.mailinglist"));
      out.write('"');
      out.write('>');
      out.print(ResourceLoader.GetResource(session, "navbar.help.mailinglist"));
      out.write("</a></li>\r\n");
      out.write("                                        <li><a href=\"http://juddi.apache.org/source.html\" title=\"");
      out.print(ResourceLoader.GetResource(session, "navbar.help.source"));
      out.write('"');
      out.write('>');
      out.print(ResourceLoader.GetResource(session, "navbar.help.source"));
      out.write("</a></li>\r\n");
      out.write("                                        <li><a href=\"about.jsp\" title=\"");
      out.print(ResourceLoader.GetResource(session, "navbar.help.about.tooltip"));
      out.write('"');
      out.write('>');
      out.print(ResourceLoader.GetResource(session, "navbar.help.about"));
      out.write("</a></li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                </li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                            <div id=\"loginfield\">\r\n");
      out.write("                                ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"navbar-form pull-right\">\r\n");
      out.write("\r\n");
      out.write("    ");

        if (session.getAttribute("username") != null && session.getAttribute("password") != null
                && ((String) session.getAttribute("username")).length() > 0 && ((String) session.getAttribute("password")).length() > 0) {
            //we're probably logged in

    
      out.write("\r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("        loggedin = true;\r\n");
      out.write("    </script>\r\n");
      out.write("    <a class=\"btn\" title=\"");
      out.print(ResourceLoader.GetResource(session, "navbar.login.logout"));
      out.write("\" href=\"javascript:logout();\">\r\n");
      out.write("        ");

                if (!request.isSecure()) {
            
      out.write("\r\n");
      out.write("            <i class=\"icon-warning-sign\" title=\"");
      out.print(ResourceLoader.GetResource(session, "warning.ssl"));
      out.write("\"></i>\r\n");
      out.write("            ");

                }
            
      out.write("\r\n");
      out.write("        \r\n");
      out.write("        <i class=\"icon-user\"></i>\r\n");
      out.write("        ");

            out.write(ResourceLoader.GetResource(session, "items.welcome") + " " + StringEscapeUtils.escapeHtml((String) session.getAttribute("username")) + "</a>");

        } else {
        
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <script type=\"text/javascript\">\r\n");
      out.write("            loggedin = false;\r\n");
      out.write("        </script>\r\n");
      out.write("\r\n");
      out.write("        <input class=\"span2\" type=\"text\" placeholder=\"");
      out.print(ResourceLoader.GetResource(session, "navbar.login.username"));
      out.write("\" name=\"username\" id=\"username\">\r\n");
      out.write("        <input class=\"span2\" type=\"password\" placeholder=\"");
      out.print(ResourceLoader.GetResource(session, "navbar.login.password"));
      out.write("\" name=\"password\" id=\"password\">\r\n");
      out.write("        <button type=\"button\" onclick=\"javascript:Login();\" class=\"btn\" id=\"loginbutton\">\r\n");
      out.write("            ");

                if (!request.isSecure() ||  !UddiAdminHub.getInstance(application, session).isSecure()) {
            
      out.write("\r\n");
      out.write("            <i class=\"icon-warning-sign\" title=\"");
      out.print(ResourceLoader.GetResource(session, "warning.ssl"));
      out.write("\"></i>\r\n");
      out.write("            ");

                }
            
      out.write("\r\n");
      out.write("            ");
      out.print(ResourceLoader.GetResource(session, "navbar.login.button"));
      out.write("\r\n");
      out.write("        </button>\r\n");
      out.write("        ");

            }
        
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("        \r\n");
      out.write("            \r\n");
      out.write("<div class=\"modal hide fade container\" id=\"loginfailure\">\r\n");
      out.write("    <div class=\"modal-header\">\r\n");
      out.write("        <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-hidden=\"true\">&times;</button>\r\n");
      out.write("        <h3>");
      out.print(ResourceLoader.GetResource(session, "errors.generic"));
      out.write("</h3>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"modal-body\">\r\n");
      out.write("            <i class=\"icon-4x icon-thumbs-down\"></i><br>\r\n");
      out.write("            <div id=\"loginfailuredetails\"></div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"modal-footer\">\r\n");
      out.write("            <button type=\"button\" class=\"btn\" data-dismiss=\"modal\" >");
      out.print(ResourceLoader.GetResource(session, "modal.close"));
      out.write("</button>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>");
      out.write("\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div><!--/.nav-collapse -->\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("        <!-- Main hero unit for a primary marketing message or call to action -->\r\n");
      out.write("        <div class=\"well\">\r\n");
      out.write("                <h1>");
      out.print(ResourceLoader.GetResource(session, "pages.home.admin"));
      out.write("</h1>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- Example row of columns -->\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                <div class=\"span12\">\r\n");
      out.write("                        ");
 UddiAdminHub x = UddiAdminHub.getInstance(application, session);
                        
                        
      out.write(" \r\n");
      out.write("                        ");
      out.print(ResourceLoader.GetResource(session, "pages.admin.content"));
      out.write("\r\n");
      out.write("                        <br>\r\n");
      out.write("                        <select onchange=\"toggledivs();\" id=\"divselector\">\r\n");
      out.write("                                \r\n");
      out.write("                                <option>------ Subscription Management -----</option>\r\n");
      out.write("                                <option>get_AllClientSubscriptionInfo</option>\r\n");
      out.write("                                <option>delete_ClientSubscriptionInfo</option>\r\n");
      out.write("                                <option>invoke_SyncSubscription</option>\r\n");
      out.write("                                <option>save_ClientSubscriptionInfo</option>\r\n");
      out.write("                                \r\n");
      out.write("                                <option>admin_SaveSubscription</option>\r\n");
      out.write("                                <option>admin_DeleteSubscription</option>\r\n");
      out.write("                                \r\n");
      out.write("                                <option>get_AllNodes</option>\r\n");
      out.write("                                <option>save_Node</option>\r\n");
      out.write("                                <option>delete_Node</option>\r\n");
      out.write("                                \r\n");
      out.write("                                <option>get_AllClerks</option>\r\n");
      out.write("                                <option>save_Clerk</option>\r\n");
      out.write("                                <option>delete_Clerk</option>\r\n");
      out.write("                                \r\n");
      out.write("                                <option>------ Publisher/User Management -----</option>\r\n");
      out.write("                                <option>getAllPublisherDetail</option>\r\n");
      out.write("                                <option>get_publisherDetail</option>\r\n");
      out.write("                                <option>delete_publisher</option>\r\n");
      out.write("                                <option>save_publisher</option>\r\n");
      out.write("                                \r\n");
      out.write("                                \r\n");
      out.write("                                \r\n");
      out.write("                                <option>------ Node Management -----</option>\r\n");
      out.write("                                <option>set_ReplicationNodes</option>\r\n");
      out.write("                                <option>get_ReplicationNodes</option>\r\n");
      out.write("                                <option>get_EntityHistory</option>\r\n");
      out.write("                                <option>change_NodeID</option>\r\n");
      out.write("                                <option>getFailedReplicationChangeRecords</option>\r\n");
      out.write("\r\n");
      out.write("                                <option>------ Backup/Restore Management -----</option>\r\n");
      out.write("                                <option>admin_SaveBusiness</option>\r\n");
      out.write("                                <option>admin_SaveTModel</option>\r\n");
      out.write("                                <option>adminDelete_tmodel</option>                                 \r\n");
      out.write("                                <option>send_EmailTest</option>\r\n");
      out.write("                               \r\n");
      out.write("                                \r\n");
      out.write("                        </select>\r\n");
      out.write("\r\n");
      out.write("                        <div>\r\n");
      out.write("                                <div id=\"adminDelete_tmodel\" style=\"display:none\">\r\n");
      out.write("                                        <input type=\"text\" id=\"adminDelete_tmodelKEY\" class=\"forminput\" placeholder=\"Enter tModel Key\">\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div id=\"delete_ClientSubscriptionInfo\"  style=\"display:none\">\r\n");
      out.write("                                        <input type=\"text\" id=\"delete_ClientSubscriptionInfoKEY\" class=\"forminput\" placeholder=\"Enter subscription Key\">\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div id=\"invoke_SyncSubscription\" style=\"display:none\">\r\n");
      out.write("                                        ");
      out.print(ResourceLoader.GetResource(session, "items.noauthtoken"));
      out.write("  <br>\r\n");
      out.write("                                        <textarea rows=\"4\" cols=\"80\" id=\"invoke_SyncSubscriptionXML\" class=\"forminput\" placeholder=\"Enter subscription XML\"></textarea>\r\n");
      out.write("\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div id=\"delete_publisher\" style=\"display:none\">\r\n");
      out.write("                                        <input type=\"text\"  class=\"forminput\" id=\"delete_publisherKEY\" placeholder=\"Enter publisher id\">\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div id=\"getAllPublisherDetail\" style=\"display:none\">\r\n");
      out.write("                                        ");
      out.print(ResourceLoader.GetResource(session, "items.noinput"));
      out.write("\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div id=\"get_publisherDetail\" style=\"display:none\">\r\n");
      out.write("                                        <input type=\"text\" id=\"get_publisherDetailKEY\"  class=\"forminput\" placeholder=\"Enter publisher id\">\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div id=\"save_ClientSubscriptionInfo\" style=\"display:none\">\r\n");
      out.write("                                        ");
      out.print(ResourceLoader.GetResource(session, "items.noauthtoken"));
      out.write("<br>\r\n");
      out.write("                                        <textarea rows=\"4\" cols=\"80\" id=\"ClientSubscriptionInfoDetailXML\" class=\"forminput\" placeholder=\"Enter subscription XML\">");
      out.print(StringEscapeUtils.escapeHtml(x.getSampleSave_ClientSubscriptionInfo()));
      out.write("</textarea>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div id=\"save_publisher\" style=\"display:none\">\r\n");
      out.write("                                        ");
      out.print(ResourceLoader.GetResource(session, "items.name"));
      out.write(" <input type=\"text\" id=\"savePublisherNAME\"  class=\"forminput\" placeholder=\"Enter name\"><br>\r\n");
      out.write("                                        ");
      out.print(ResourceLoader.GetResource(session, "items.email"));
      out.write("  <input type=\"text\" id=\"savePublisherEMAIL\"  class=\"forminput\" placeholder=\"Enter email\"><br>\r\n");
      out.write("                                        ");
      out.print(ResourceLoader.GetResource(session, "items.authorizedname"));
      out.write("  <input type=\"text\" id=\"savePublisherAuthorizedName\"  class=\"forminput\" placeholder=\"Enter Authorized Name (username)\"><br>\r\n");
      out.write("                                        ");
      out.print(ResourceLoader.GetResource(session, "items.publisher.admin"));
      out.write("  <input type=\"checkbox\" id=\"savePublisherIsAdmin\"   ><br>\r\n");
      out.write("                                        ");
      out.print(ResourceLoader.GetResource(session, "items.enable"));
      out.write("  <input type=\"checkbox\" id=\"savePublisherIsEnabled\"  ><br>\r\n");
      out.write("                                        ");
      out.print(ResourceLoader.GetResource(session, "max.bindings.per.service"));
      out.write(" <input type=\"text\" id=\"savePublisherMaxBindings\" placeholder=\"100\"  class=\"forminput\"><br>\r\n");
      out.write("                                        ");
      out.print(ResourceLoader.GetResource(session, "max.services.per.business"));
      out.write(" <input type=\"text\" id=\"savePublisherMaxServices\" placeholder=\"1000\" class=\"forminput\"><br>\r\n");
      out.write("                                        ");
      out.print(ResourceLoader.GetResource(session, "max.business"));
      out.write(" <input type=\"text\" id=\"savePublisherMaxBusiness\" placeholder=\"1000\"  class=\"forminput\"><br>\r\n");
      out.write("                                        ");
      out.print(ResourceLoader.GetResource(session, "max.tmodel"));
      out.write(" <input type=\"text\" id=\"savePublisherMaxTModels\" placeholder=\"1000\" class=\"forminput\"><br>\r\n");
      out.write("                                        <br>\r\n");
      out.write("                                        ");
      out.print(ResourceLoader.GetResource(session, "pages.admin.max"));
      out.write("\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div id=\"save_Node\" style=\"display:none\">\r\n");
      out.write("\r\n");
      out.write("                                        ");
      out.print(ResourceLoader.GetResource(session, "items.clientname"));
      out.write(" <input type=\"text\" id=\"NODEsetClientName\"  class=\"forminput\" placeholder=\"Client Name\"><br>\r\n");
      out.write("                                        ");
      out.print(ResourceLoader.GetResource(session, "items.name"));
      out.write(" <input type=\"text\" id=\"NODEsetName\"  class=\"forminput\" placeholder=\"Enter name\"><br>\r\n");
      out.write("\r\n");
      out.write("                                        ");
      out.print(ResourceLoader.GetResource(session, "items.description"));
      out.write(" <input type=\"text\" id=\"NODEsetDescription\"  class=\"forminput\" placeholder=\"Enter description\"><br>\r\n");
      out.write("                                        Factory Initial <input type=\"text\" id=\"NODEsetFactoryInitial\"  class=\"forminput\" placeholder=\"only needed for RMI transport\"><br>\r\n");
      out.write("                                        Factory URL Packages <input type=\"text\" id=\"NODEsetFactoryURLPkgs\"  class=\"forminput\" placeholder=\"only needed for RMI transport\"><br>\r\n");
      out.write("                                        Factory Naming Provider <input type=\"text\" id=\"NODEsetFactoryNamingProvider\"  class=\"forminput\" placeholder=\"only needed for RMI transport\"><br>\r\n");
      out.write("                                        ");
      out.print(ResourceLoader.GetResource(session, "items.transport"));
      out.write(" <input type=\"text\" id=\"NODEsetProxyTransport\"  class=\"forminput\" placeholder=\"org.apache.juddi.v3.client.transport.JAXWSTransport\" value=\"org.apache.juddi.v3.client.transport.JAXWSTransport\"><br>\r\n");
      out.write("                                        ");
      out.print(ResourceLoader.GetResource(session, "items.inquiry"));
      out.write(" <input type=\"text\" id=\"NODEsetInquiryUrl\"  class=\"forminput\" placeholder=\"http://localhost:8080/juddiv3/services/inquiry\" value=\"http://localhost:8080/juddiv3/services/inquiry\"><br>\r\n");
      out.write("                                        ");
      out.print(ResourceLoader.GetResource(session, "items.publish"));
      out.write(" <input type=\"text\" id=\"NODEsetPublishUrl\"  class=\"forminput\" placeholder=\"http://localhost:8080/juddiv3/services/publish\" value=\"http://localhost:8080/juddiv3/services/publish\"><br>\r\n");
      out.write("                                        ");
      out.print(ResourceLoader.GetResource(session, "items.security"));
      out.write(" <input type=\"text\" id=\"NODEsetSecurityUrl\"  class=\"forminput\" placeholder=\"http://localhost:8080/juddiv3/services/security\" value=\"http://localhost:8080/juddiv3/services/security\"><br>\r\n");
      out.write("                                        ");
      out.print(ResourceLoader.GetResource(session, "items.subscription.list"));
      out.write(" <input type=\"text\" id=\"NODEsetSubscriptionListenerUrl\"  class=\"forminput\" placeholder=\"http://localhost:8080/juddiv3/services/subscription-listener\" value=\"http://localhost:8080/juddiv3/services/subscription-listener\"><br>\r\n");
      out.write("                                        ");
      out.print(ResourceLoader.GetResource(session, "items.subscription"));
      out.write(" <input type=\"text\" id=\"NODEsetSubscriptionUrl\"  class=\"forminput\" placeholder=\"http://localhost:8080/juddiv3/services/subscription\" value=\"http://localhost:8080/juddiv3/services/subscription\"><br>\r\n");
      out.write("                                        ");
      out.print(ResourceLoader.GetResource(session, "items.custodytransfer"));
      out.write(" <input type=\"text\" id=\"NODEsetCustodyTransferUrl\"  class=\"forminput\" placeholder=\"http://localhost:8080/juddiv3/services/custody-transfer\" value=\"http://localhost:8080/juddiv3/services/custody-transfer\"><br>\r\n");
      out.write("                                        ");
      out.print(ResourceLoader.GetResource(session, "items.replication"));
      out.write(" <input type=\"text\" id=\"NODEsetReplicationUrl\"  class=\"forminput\" placeholder=\"http://localhost:8080/juddiv3/services/replication\" value=\"http://localhost:8080/juddiv3/services/replication\"><br>\r\n");
      out.write("                                        jUDDI API <input type=\"text\" id=\"NODEsetJuddiApiUrl\"  class=\"forminput\" placeholder=\"http://localhost:8080/juddiv3/services/juddi-api\" value=\"http://localhost:8080/juddiv3/services/juddi-api\"><br>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div id=\"save_Clerk\" style=\"display:none\">\r\n");
      out.write("                                        ");
      out.print(ResourceLoader.GetResource(session, "items.name"));
      out.write(" <input type=\"text\" id=\"CLERKsetName\"  class=\"forminput\" placeholder=\"Enter name\"><br>\r\n");
      out.write("                                        ");
      out.print(ResourceLoader.GetResource(session, "items.authorizedname"));
      out.write(" <input type=\"text\" id=\"CLERKsetPublisher\"  class=\"forminput\" placeholder=\"Enter Authorized Name (username)\"><br>\r\n");
      out.write("                                        ");
      out.print(ResourceLoader.GetResource(session, "navbar.login.password"));
      out.write(" <input type=\"password\" id=\"CLERKsetPassword\"  class=\"forminput\" placeholder=\"Enter password\"><br>\r\n");
      out.write("                                        <hr>\r\n");
      out.write("                                        ");
      out.print(ResourceLoader.GetResource(session, "items.clientname"));
      out.write(" <input type=\"text\" id=\"CLERKNODEsetClientName\"  class=\"forminput\" placeholder=\"Client Name\"><br>\r\n");
      out.write("                                        ");
      out.print(ResourceLoader.GetResource(session, "items.name"));
      out.write(" <input type=\"text\" id=\"CLERKNODEsetName\"  class=\"forminput\" placeholder=\"Enter name\"><br>\r\n");
      out.write("\r\n");
      out.write("                                        ");
      out.print(ResourceLoader.GetResource(session, "items.description"));
      out.write(" <input type=\"text\" id=\"CLERKNODEsetDescription\"  class=\"forminput\" placeholder=\"Enter description\"><br>\r\n");
      out.write("                                        Factory Initial <input type=\"text\" id=\"CLERKNODEsetFactoryInitial\"  class=\"forminput\" placeholder=\"only needed for RMI transport\"><br>\r\n");
      out.write("                                        Factory URL Packages <input type=\"text\" id=\"CLERKNODEsetFactoryURLPkgs\"  class=\"forminput\" placeholder=\"only needed for RMI transport\"><br>\r\n");
      out.write("                                        Factory Naming Provider <input type=\"text\" id=\"CLERKNODEsetFactoryNamingProvider\"  class=\"forminput\" placeholder=\"only needed for RMI transport\"><br>\r\n");
      out.write("                                        ");
      out.print(ResourceLoader.GetResource(session, "items.transport"));
      out.write(" <input type=\"text\" id=\"CLERKNODEsetProxyTransport\"  class=\"forminput\" placeholder=\"org.apache.juddi.v3.client.transport.JAXWSTransport\" value=\"org.apache.juddi.v3.client.transport.JAXWSTransport\"><br>\r\n");
      out.write("                                        ");
      out.print(ResourceLoader.GetResource(session, "items.inquiry"));
      out.write(" <input type=\"text\" id=\"CLERKNODEsetInquiryUrl\"  class=\"forminput\" placeholder=\"http://localhost:8080/juddiv3/services/inquiry\" value=\"http://localhost:8080/juddiv3/services/inquiry\"><br>\r\n");
      out.write("                                        ");
      out.print(ResourceLoader.GetResource(session, "items.publish"));
      out.write(" <input type=\"text\" id=\"CLERKNODEsetPublishUrl\"  class=\"forminput\" placeholder=\"http://localhost:8080/juddiv3/services/publish\" value=\"http://localhost:8080/juddiv3/services/publish\"><br>\r\n");
      out.write("                                        ");
      out.print(ResourceLoader.GetResource(session, "items.security"));
      out.write(" <input type=\"text\" id=\"CLERKNODEsetSecurityUrl\"  class=\"forminput\" placeholder=\"http://localhost:8080/juddiv3/services/security\" value=\"http://localhost:8080/juddiv3/services/security\"><br>\r\n");
      out.write("                                        ");
      out.print(ResourceLoader.GetResource(session, "items.subscription.list"));
      out.write(" <input type=\"text\" id=\"CLERKNODEsetSubscriptionListenerUrl\"  class=\"forminput\" placeholder=\"http://localhost:8080/juddiv3/services/subscription-listener\" value=\"http://localhost:8080/juddiv3/services/subscription-listener\"><br>\r\n");
      out.write("                                        ");
      out.print(ResourceLoader.GetResource(session, "items.subscription"));
      out.write(" <input type=\"text\" id=\"CLERKNODEsetSubscriptionUrl\"  class=\"forminput\" placeholder=\"http://localhost:8080/juddiv3/services/subscription\" value=\"http://localhost:8080/juddiv3/services/subscription\"><br>\r\n");
      out.write("                                        ");
      out.print(ResourceLoader.GetResource(session, "items.custodytransfer"));
      out.write(" <input type=\"text\" id=\"CLERKNODEsetCustodyTransferUrl\"  class=\"forminput\" placeholder=\"http://localhost:8080/juddiv3/services/custody-transfer\" value=\"http://localhost:8080/juddiv3/services/custody-transfer\"><br>\r\n");
      out.write("                                        ");
      out.print(ResourceLoader.GetResource(session, "items.replication"));
      out.write(" <input type=\"text\" id=\"CLERKNODEsetReplicationUrl\"  class=\"forminput\" placeholder=\"http://localhost:8080/juddiv3/services/replication\" value=\"http://localhost:8080/juddiv3/services/replication\"><br>\r\n");
      out.write("                                        jUDDI API <input type=\"text\" id=\"CLERKNODEsetJuddiApiUrl\"  class=\"forminput\" placeholder=\"http://localhost:8080/juddiv3/services/juddi-api\" value=\"http://localhost:8080/juddiv3/services/juddi-api\"><br>\r\n");
      out.write("\r\n");
      out.write("                                </div>\r\n");
      out.write("                                        \r\n");
      out.write("                                        \r\n");
      out.write("                                        \r\n");
      out.write("                                <div id=\"send_EmailTest\" style=\"display:none\">\r\n");
      out.write("                                ");
      out.print(ResourceLoader.GetResource(session, "items.email"));
      out.write("  <input type=\"text\" id=\"send_EmailTestEMAIL\"  class=\"forminput\" placeholder=\"Enter email\"><br>    \r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div id=\"get_AllNodes\" style=\"display:none\">\r\n");
      out.write("                                    No input required.\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div id=\"get_AllClerks\" style=\"display:none\">\r\n");
      out.write("                                    No input required.\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div id=\"delete_Node\" style=\"display:none\">\r\n");
      out.write("                                    Node name <input type=\"text\" id=\"delete_NodeName\"  class=\"forminput\" placeholder=\"Node name\"><br>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div id=\"delete_Clerk\" style=\"display:none\">\r\n");
      out.write("                                    Clerk name <input type=\"text\" id=\"delete_ClerkName\"  class=\"forminput\" placeholder=\"Clerk name\"><br>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div id=\"admin_DeleteSubscription\" style=\"display:none\">\r\n");
      out.write("                                   Subscription Key <input type=\"text\" id=\"admin_DeleteSubscriptionKey\"  class=\"forminput\" placeholder=\"Subscription Key\"><br>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div id=\"admin_SaveBusiness\" style=\"display:none\">\r\n");
      out.write("                                     ");
      out.print(ResourceLoader.GetResource(session, "items.noauthtoken"));
      out.write("  <br>\r\n");
      out.write("                                        <textarea rows=\"4\" cols=\"80\" id=\"admin_SaveBusinessXML\" class=\"forminput\" placeholder=\"Enter save business XML\"></textarea>\r\n");
      out.write("\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div id=\"admin_SaveTModel\" style=\"display:none\">\r\n");
      out.write("                                     ");
      out.print(ResourceLoader.GetResource(session, "items.noauthtoken"));
      out.write("  <br>\r\n");
      out.write("                                        <textarea rows=\"4\" cols=\"80\" id=\"admin_SaveTModelXML\" class=\"forminput\" placeholder=\"Enter save tmodel XML\"></textarea>\r\n");
      out.write("\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div id=\"get_AllClientSubscriptionInfo\" style=\"display:none\">\r\n");
      out.write("                                    No input required.\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div id=\"set_ReplicationNodes\" style=\"display:none\">\r\n");
      out.write("                                    \r\n");
      out.write("                                         ");
      out.print(ResourceLoader.GetResource(session, "items.noauthtoken"));
      out.write("  <br>\r\n");
      out.write("                                        <textarea rows=\"4\" cols=\"80\" id=\"set_ReplicationNodesXML\" class=\"forminput\" placeholder=\"Enter replication config XML\"></textarea>\r\n");
      out.write("\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div id=\"get_ReplicationNodes\" style=\"display:none\">\r\n");
      out.write("                                    No input required.\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div id=\"admin_SaveSubscription\" style=\"display:none\">\r\n");
      out.write("                                    \r\n");
      out.write("                                         ");
      out.print(ResourceLoader.GetResource(session, "items.noauthtoken"));
      out.write("  <br>\r\n");
      out.write("                                        <textarea rows=\"4\" cols=\"80\" id=\"admin_SaveSubscriptionXML\" class=\"forminput\" placeholder=\"Enter save subscription XML\"></textarea>\r\n");
      out.write("\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div id=\"get_EntityHistory\" style=\"display:none\">\r\n");
      out.write("                                   Entity Key <input type=\"text\" id=\"get_EntityHistoryKey\"  class=\"forminput\" placeholder=\"Entity Key\"><br>\r\n");
      out.write("                                   Records to fetch <input type=\"text\" id=\"get_EntityHistoryMaxCount\"  class=\"forminput\" value=\"25\"><br>\r\n");
      out.write("                                   Offset <input type=\"text\" id=\"get_EntityHistoryOffset\"  class=\"forminput\" value=\"0\"><br>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                        \r\n");
      out.write("                                <div id=\"change_NodeID\" style=\"display:none\">\r\n");
      out.write("                                    This will change the current node's identifier. During the transaction, no one will be able to modify items stored in the database.\r\n");
      out.write("                                    This option is not available if this node is configured for replication. It must be removed from the replication configuration on all nodes before renaming.\r\n");
      out.write("                                    <br><br>\r\n");
      out.write("                                    Note: Depending on how jUDDI was deployed, you may have to manually edit the juddiv3.xml config file, then restart jUDDI after this process is complete.<br><br>\r\n");
      out.write("                                    New Node ID <input type=\"text\" id=\"change_NodeIDKey\"  class=\"forminput\" placeholder=\"Node ID\" value=\"");
      out.print(StringEscapeUtils.escapeHtml( AppConfig.getConfiguration().getString(Property.JUDDI_NODE_ID)));
      out.write("\"><br>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div id=\"getFailedReplicationChangeRecords\" style=\"display:none\">\r\n");
      out.write("                                    Records to fetch <input type=\"text\" id=\"getFailedReplicationChangeRecordsMaxCount\"  class=\"forminput\" value=\"5\"><br>\r\n");
      out.write("                                    Offset <input type=\"text\" id=\"getFailedReplicationChangeRecordsOffset\"  class=\"forminput\" value=\"0\"><br>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                        \r\n");
      out.write("                                \r\n");
      out.write("                               \r\n");
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("                            \r\n");
      out.write("                        <script type=\"text/javascript\">\r\n");
      out.write("                                function toggledivs()\r\n");
      out.write("                                {\r\n");
      out.write("                                        var x = $(\"#divselector\").val();\r\n");
      out.write("                                        //alert(x);\r\n");
      out.write("                                        $(\"#adminDelete_tmodel\").hide();\r\n");
      out.write("                                        $(\"#delete_ClientSubscriptionInfo\").hide();\r\n");
      out.write("                                        $(\"#delete_publisher\").hide();\r\n");
      out.write("                                        $(\"#getAllPublisherDetail\").hide();\r\n");
      out.write("                                        $(\"#get_publisherDetail\").hide();\r\n");
      out.write("                                        $(\"#invoke_SyncSubscription\").hide();\r\n");
      out.write("                                        $(\"#save_ClientSubscriptionInfo\").hide();\r\n");
      out.write("                                        $(\"#save_publisher\").hide();\r\n");
      out.write("                                        $(\"#save_Clerk\").hide();\r\n");
      out.write("                                        $(\"#save_Node\").hide();\r\n");
      out.write("                                        \r\n");
      out.write("                                        \r\n");
      out.write("                                        $(\"#send_EmailTest\").hide();\r\n");
      out.write("                                        $(\"#get_AllNodes\").hide();\r\n");
      out.write("                                        $(\"#get_AllClerks\").hide();\r\n");
      out.write("                                        $(\"#delete_Node\").hide();\r\n");
      out.write("                                        $(\"#delete_Clerk\").hide();\r\n");
      out.write("                                        $(\"#admin_DeleteSubscription\").hide();\r\n");
      out.write("                                        $(\"#admin_SaveBusiness\").hide();\r\n");
      out.write("                                        $(\"#admin_SaveTModel\").hide();\r\n");
      out.write("                                        $(\"#get_AllClientSubscriptionInfo\").hide();\r\n");
      out.write("                                        $(\"#set_ReplicationNodes\").hide();\r\n");
      out.write("                                        $(\"#get_ReplicationNodes\").hide();\r\n");
      out.write("                                        $(\"#admin_SaveSubscription\").hide();\r\n");
      out.write("                                        $(\"#get_EntityHistory\").hide();\r\n");
      out.write("                                        $(\"#change_NodeID\").hide();\r\n");
      out.write("                                        $(\"#getFailedReplicationChangeRecords\").hide();\r\n");
      out.write("                                       \r\n");
      out.write("                        \r\n");
      out.write("                                        $(\"#\" + x).show();\r\n");
      out.write("                                        \r\n");
      out.write("                                        //get a samle xml doc\r\n");
      out.write("                                        \r\n");
      out.write("                                       // var x = $(\"#\" + select).val();\r\n");
      out.write("                                        var url = 'ajax/advanced.jsp';\r\n");
      out.write("\r\n");
      out.write("                                        var postbackdata = new Array();\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                                        postbackdata.push({\r\n");
      out.write("                                            name: \"advancedaction\",\r\n");
      out.write("                                            value: \"getdefaultrequest\"\r\n");
      out.write("                                        });\r\n");
      out.write("\r\n");
      out.write("                                        postbackdata.push({\r\n");
      out.write("                                            name: \"nonce\",\r\n");
      out.write("                                            value: $(\"#nonce\").val()\r\n");
      out.write("                                        });\r\n");
      out.write("\r\n");
      out.write("                                       \r\n");
      out.write("                                        postbackdata.push({\r\n");
      out.write("                                            name: \"method\",\r\n");
      out.write("                                            value: x\r\n");
      out.write("                                        });\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                                        var request = $.ajax({\r\n");
      out.write("                                            url: url,\r\n");
      out.write("                                            type: \"POST\",\r\n");
      out.write("                                            //  data\" + i18n_type + \": \"html\", \r\n");
      out.write("                                            cache: false,\r\n");
      out.write("                                            //  processData: false,f\r\n");
      out.write("                                            data: postbackdata\r\n");
      out.write("                                        });\r\n");
      out.write("\r\n");
      out.write("                                        $(\"#resultsDiv\").html(\"\");\r\n");
      out.write("                                        request.done(function(msg) {\r\n");
      out.write("                                            window.console && console.log('postback done ' + url);\r\n");
      out.write("                                            //trim it\r\n");
      out.write("                                            $(\"#\" + x + \"XML\").html(msg.replace(/^\\s+|\\s+$/g, ''));\r\n");
      out.write("                                        });\r\n");
      out.write("\r\n");
      out.write("                                        request.fail(function(jqXHR, textStatus) {\r\n");
      out.write("                                            window.console && console.log('postback failed ' + url + ' ' + jqXHR.responseText + textStatus);\r\n");
      out.write("                                            //$(\"#adminresults\").html(jqXHR.responseText + textStatus);\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                                        });\r\n");
      out.write("                                }\r\n");
      out.write("                                toggledivs();//run when the page loads\r\n");
      out.write("                                function submitform() {\r\n");
      out.write("                                    $(\"#resultsDiv\").val(\"Please wait...\");\r\n");
      out.write("                                        var url = 'ajax/go.jsp';\r\n");
      out.write("\r\n");
      out.write("                                        var postbackdata = new Array();\r\n");
      out.write("\r\n");
      out.write("                                        var x = $(\"#divselector\").val();\r\n");
      out.write("                                        postbackdata.push({\r\n");
      out.write("                                                name: \"soapaction\",\r\n");
      out.write("                                                value: x\r\n");
      out.write("                                        });\r\n");
      out.write("\r\n");
      out.write("                                        postbackdata.push({\r\n");
      out.write("                                                name: \"nonce\",\r\n");
      out.write("                                                value: $(\"#nonce\").val()\r\n");
      out.write("                                        });\r\n");
      out.write("\r\n");
      out.write("                                        $(\".forminput\").each(function()\r\n");
      out.write("                                        {\r\n");
      out.write("                                                var id = $(this).attr(\"id\");\r\n");
      out.write("                                                var value = $(this).val();\r\n");
      out.write("                                                if (value === null || value === \"\" || value === undefined)\r\n");
      out.write("                                                        value=$(this).text();\r\n");
      out.write("                                                postbackdata.push({\r\n");
      out.write("                                                        name: id,\r\n");
      out.write("                                                        value: value\r\n");
      out.write("                                                });\r\n");
      out.write("                                        });\r\n");
      out.write("                                     \r\n");
      out.write("                                        postbackdata.push({\r\n");
      out.write("                                                name: \"savePublisherIsEnabled\",\r\n");
      out.write("                                                value: $('#savePublisherIsEnabled').prop(\"checked\")\r\n");
      out.write("                                        });\r\n");
      out.write("                                        postbackdata.push({\r\n");
      out.write("                                                name: \"savePublisherIsAdmin\",\r\n");
      out.write("                                                value: $('#savePublisherIsAdmin').prop(\"checked\")\r\n");
      out.write("                                        });\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                                        var request = $.ajax({\r\n");
      out.write("                                                url: url,\r\n");
      out.write("                                                type: \"POST\",\r\n");
      out.write("                                                //  data\" + i18n_type + \": \"html\", \r\n");
      out.write("                                                cache: false,\r\n");
      out.write("                                                //  processData: false,f\r\n");
      out.write("                                                data: postbackdata\r\n");
      out.write("                                        });\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                                        request.done(function(msg) {\r\n");
      out.write("                                                window.console && console.log('postback done ' + url);\r\n");
      out.write("                                                if (StringStartsWith(msg.trim(),\"Error\")){\r\n");
      out.write("                                                     $(\"#adminresults\").html(msg);\r\n");
      out.write("                                                    $('#adminresultsmodal').modal();\r\n");
      out.write("                                                }\r\n");
      out.write("                                                else\r\n");
      out.write("                                                {\r\n");
      out.write("                                                    $(\"#resultsDiv\").html(msg);\r\n");
      out.write("                                                    location.hash = \"#resultsAnchor\";\r\n");
      out.write("                                                }\r\n");
      out.write("                                        });\r\n");
      out.write("\r\n");
      out.write("                                        request.fail(function(jqXHR, textStatus) {\r\n");
      out.write("                                                window.console && console.log('postback failed ' + url);\r\n");
      out.write("                                                $(\"#adminresults\").html(jqXHR.responseText + textStatus);\r\n");
      out.write("                                                $('#adminresultsmodal').modal();\r\n");
      out.write("\r\n");
      out.write("                                        });\r\n");
      out.write("                                }\r\n");
      out.write("                                \r\n");
      out.write("                                function StringStartsWith(source, str){\r\n");
      out.write("                                    \r\n");
      out.write("                                      return source.slice(0, str.length) == str;\r\n");
      out.write("                                    \r\n");
      out.write("                                  }\r\n");
      out.write("                        </script>\r\n");
      out.write("                        <br>\r\n");
      out.write("                        ");
      out.print(ResourceLoader.GetResource(session, "pages.admin.notes"));
      out.write("\r\n");
      out.write("\r\n");
      out.write("                        <br>\r\n");
      out.write("                        <a href=\"javascript:submitform();\" class=\"btn btn-primary\">");
      out.print(ResourceLoader.GetResource(session, "actions.go"));
      out.write("</a><br>\r\n");
      out.write("                        \r\n");
      out.write("                        <hr>\r\n");
      out.write("                        <br><a name=\"resultsAnchor\"></a>\r\n");
      out.write("                            <div id=\"resultsDiv\"></div>\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <div class=\"modal hide fade container \" id=\"adminresultsmodal\">\r\n");
      out.write("                <div class=\"modal-header\">\r\n");
      out.write("                        <a href=\"javascript:$('#adminresultsmodal').modal('hide');\" class=\"close\" data-dismiss=\"modal\" aria-hidden=\"true\">&times;</a>\r\n");
      out.write("                        <h3>");
      out.print(ResourceLoader.GetResource(session, "items.results"));
      out.write("</h3>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"modal-body\" align=\"center\">\r\n");
      out.write("                        <div id=\"adminresults\"></div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"modal-footer\">\r\n");
      out.write("                        <a href=\"javascript:$('#adminresultsmodal').modal('hide');\" class=\"btn btn-primary\" data-dismiss=\"modal\">");
      out.print(ResourceLoader.GetResource(session, "modal.close"));
      out.write("</a>\r\n");
      out.write("                </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</div> <!-- /container -->\r\n");
      out.write("</form>\r\n");
      out.write("<div style=\"\r\n");
      out.write("     padding: 0px 0px 0px 0px; bottom: 0px; margin: 0px 0px 0px 0px; width:100%; text-align: center; position: fixed; \r\n");
      out.write("     background-color: white; \r\n");
      out.write("     \"><center><footer>v");

     out.write(StringEscapeUtils.escapeHtml(org.apache.juddi.v3.client.Release.getRegistryVersion()));
     
      out.write(" - <a href=\"http://www.apache.org\">");
      out.print(ResourceLoader.GetResource(session, "footer.apachecopyright"));
      out.write("</a></footer></center></div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
