/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.82
 * Generated at: 2018-03-05 18:01:29 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import org.apache.juddi.adminconsole.hub.UddiAdminHub;
import org.apache.juddi.adminconsole.resources.ResourceLoader;
import org.apache.juddi.adminconsole.hub.UddiAdminHub;
import org.apache.juddi.adminconsole.CrossSiteRequestForgeryException;
import org.apache.juddi.adminconsole.hub.UddiAdminHub;
import org.apache.juddi.adminconsole.resources.ResourceLoader;
import org.apache.commons.lang.StringEscapeUtils;
import org.apache.commons.lang.StringEscapeUtils;
import java.io.IOException;
import java.util.jar.Attributes;
import java.util.jar.Manifest;
import java.io.InputStream;
import java.util.jar.JarFile;
import java.net.URL;
import java.util.Enumeration;
import org.apache.juddi.adminconsole.resources.ResourceLoader;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/admin/csrf.jsp", Long.valueOf(1477445500000L));
    _jspx_dependants.put("/admin/header-top.jsp", Long.valueOf(1477445500000L));
    _jspx_dependants.put("/admin/login.jsp", Long.valueOf(1477445500000L));
    _jspx_dependants.put("/admin/header-bottom.jsp", Long.valueOf(1477445500000L));
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");

    //this is to catch someone that bookmarked a page after selecting a language
    Cookie[] cookies2 = request.getCookies();
    if (cookies2 != null && cookies2.length > 0) {
        for (int i = 0; i < cookies2.length; i++) {
            if (cookies2[i] != null && cookies2[i].getName() != null && cookies2[i].getName().equalsIgnoreCase("locale")) {
                if (cookies2[i].getValue() != null) {
                    session.setAttribute("locale", cookies2[i].getValue());
                }
            }
        }
    }
    if (session.getAttribute("locale") == null) {
        //last chance, default to english
        session.setAttribute("locale", "en");
    }

      out.write("\r\n");
      out.write("<html lang=\"");
      out.print((String) session.getAttribute("locale"));
      out.write("\" dir=\"");
      out.print(ResourceLoader.GetResource(session, "direction"));
      out.write("\">\r\n");
      out.write("    <head>\r\n");
      out.write("        <meta charset=\"utf-8\">\r\n");
      out.write("        <title>");
      out.print(ResourceLoader.GetResource(session, "title"));
      out.write("</title>\r\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("        <meta name=\"description\" content=\"");
      out.print(ResourceLoader.GetResource(session, "description"));
      out.write("\">\r\n");
      out.write("        <meta name=\"author\" content=\"Apache Software Foundation\">\r\n");
      out.write("\r\n");
      out.write("        <link href=\"css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("        <link href=\"css/bootstrap-datetimepicker.min.css\" rel=\"stylesheet\">\r\n");
      out.write("        <link href=\"css/bootstrap-timepicker.min.css\" rel=\"stylesheet\">\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"css/font-awesome.min.css\">\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"css/ui-lightness/jquery-ui-1.10.2.custom.min.css\">\r\n");
      out.write("        <!--[if IE 7]>\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"css/font-awesome-ie7.min.css\">\r\n");
      out.write("        <![endif]-->\r\n");
      out.write("\r\n");
      out.write("        <link rel=\"shortcut icon\" href=\"favicon.ico\" />\r\n");
      out.write("        <style type=\"text/css\">\r\n");
      out.write("            body {\r\n");
      out.write("                padding-top: 60px;\r\n");
      out.write("                padding-bottom: 40px;\r\n");
      out.write("            }\r\n");
      out.write("        </style>\r\n");
      out.write("        <link href=\"css/bootstrap-responsive.min.css\" rel=\"stylesheet\">\r\n");
      out.write("        <link href=\"css/bootstrap-modal.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("        <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->\r\n");
      out.write("        <!--[if lt IE 9]>\r\n");
      out.write("          <script src=\"js/html5shiv.js\"></script>\r\n");
      out.write("        <![endif]-->\r\n");
      out.write("\r\n");
      out.write("        <!-- Fav and touch icons -->\r\n");
      out.write("\r\n");
      out.write("        <link rel=\"shortcut icon\" href=\"ico/favicon.png\">\r\n");
      out.write("        <script src=\"js/jquery-1.9.1.js\"></script>\r\n");
      out.write("        <script src=\"js/i18n.js.jsp\"></script>\r\n");
      out.write("        <script src=\"js/bootstrap.min.js\"></script>\r\n");
      out.write("        <script src=\"js/bootstrap-datetimepicker.min.js\"></script>\r\n");
      out.write("        <script src=\"js/bootstrap-timepicker.min.js\"></script>\r\n");
      out.write("        <script src=\"js/bootstrap-modalmanager.js\"></script>\r\n");
      out.write("        <script src=\"js/bootstrap-modal.js\"></script>\r\n");
      out.write("        <script src=\"js/jquery.jeditable.js\"></script>\r\n");
      out.write("        <script src=\"js/jquery-ui-1.10.2.custom.min.js\"></script>\r\n");
      out.write("        <script src=\"js/main.js\"></script>\r\n");
      out.write("    </head>\r\n");
      out.write("\r\n");
      out.write("    <body>\r\n");
      out.write("        <form id=\"uddiform\">\r\n");
      out.write("            ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

    //this is to catch someone that bookmarked a page after selecting a language
    Cookie[] cookies3 = request.getCookies();
    if (cookies3 != null && cookies3.length > 0) {
        for (int i = 0; i < cookies3.length; i++) {
            if (cookies3[i] != null && cookies3[i].getName() != null && cookies3[i].getName().equalsIgnoreCase("locale")) {
                if (cookies3[i].getValue() != null) {
                    session.setAttribute("locale", cookies3[i].getValue());
                }
            }
        }
    }
    if (session.getAttribute("locale")==null){
        //last change, default to english
        session.setAttribute("locale", "en");
    }
    String currentNonce = null;

    if (request.getMethod().equalsIgnoreCase("post")) {

        if ((request.getParameter("nonce") == null || request.getParameter("nonce").isEmpty())) {
            //reject it
            session.removeAttribute("nonce");
            response.sendRedirect("index.jsp");
            UddiAdminHub.log.warn( "CSRF Test failed, no nonce guid." + request.getRemoteAddr() + request.getRemoteUser());
            //throw new CrossSiteRequestForgeryException();
            response.sendRedirect("index.jsp");
                
                return;
        } else {

            String noncestr = (String) session.getAttribute("nonce");
            if (noncestr == null) {
                //no session variable to test against, reject it
                UddiAdminHub.log.warn( "CSRF Test failed, no session guid." + request.getRemoteAddr() + request.getRemoteUser());
                session.removeAttribute("nonce");
                //throw new CrossSiteRequestForgeryException("Cross Site Request Forgery");
                response.sendRedirect("index.jsp");
                
                return;
            }
            String postedstr = request.getParameter("nonce");

            //check session against existing nonce, if match
            //generate new one, add to page and session
            //else redirect to index page
            if (noncestr.equals(postedstr)) {
                currentNonce = noncestr;
                //OK
                // current = UUID.randomUUID();
                //session.removeAttribute("nonce");
                // session.setAttribute("nonce", current.toString());
                UddiAdminHub.log.info( "CSRF Test passed.");
            } else {
                //mismatch, reject it
                UddiAdminHub.log.warn( "CSRF Test failed, session did not match nonce guid." + request.getRemoteAddr() + request.getRemoteUser());
                session.removeAttribute("nonce");
                //throw new CrossSiteRequestForgeryException("Cross Site Request Forgery");
                response.sendRedirect("index.jsp");
                
                return;
            }
        }
    } else {
        //HTTP GET or otherwise message
        if ((currentNonce == null) || currentNonce.isEmpty()) {
            currentNonce = (String)session.getAttribute("nonce");
            if (currentNonce == null) {
                currentNonce = java.util.UUID.randomUUID().toString();
            }
            session.setAttribute("nonce", currentNonce);
        }

    }


      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("            <input type=\"hidden\" name=\"nonce\" id=\"nonce\" value=\"");
      out.print(StringEscapeUtils.escapeHtml((String) session.getAttribute("nonce")));
      out.write("\" />\r\n");
      out.write("            <div class=\"alert\" style=\"display:none; position: fixed; top:45px; width:80%; left: 10%; z-index: 1000; opacity: 1.0; background-color: #FFD530; color:black \" id=\"resultBar\">\r\n");
      out.write("            </div>\r\n");
      out.write("            ");

                UddiAdminHub hub = UddiAdminHub.getInstance(application, session);
            
      out.write("\r\n");
      out.write("\r\n");
      out.write("            <div class=\"navbar navbar-inverse navbar-fixed-top\">\r\n");
      out.write("                <div class=\"navbar-inner\">\r\n");
      out.write("                    <div class=\"container\">\r\n");
      out.write("                        <button type=\"button\" class=\"btn btn-navbar\" data-toggle=\"collapse\" data-target=\".nav-collapse\">\r\n");
      out.write("                            <span class=\"icon-bar\"></span>\r\n");
      out.write("                            <span class=\"icon-bar\"></span>\r\n");
      out.write("                            <span class=\"icon-bar\"></span>\r\n");
      out.write("                        </button>\r\n");
      out.write("                        <a class=\"brand\" href=\"home.jsp\" style=\"padding-left:19px; padding-top:0px; padding-bottom:0px\"><img src=\"img/logo2.png\"></a>\r\n");
      out.write("                        <div class=\"nav-collapse collapse\">\r\n");
      out.write("                            <ul class=\"nav\">\r\n");
      out.write("                                <li><a href=\"home.jsp\" ><i class=\"icon-home icon-large\"></i> ");
      out.print(ResourceLoader.GetResource(session, "navbar.home"));
      out.write("</a></li>\r\n");
      out.write("                                <li><a href=\"stats.jsp\" ><i class=\"icon-camera icon-large\"></i> Status");
//=ResourceLoader.GetResource(session, "navbar.home")
      out.write("</a></li>\r\n");
      out.write("                                <li><a href=\"configure.jsp\" ><i class=\"icon-cog icon-large\"></i> Configure");
//=ResourceLoader.GetResource(session, "navbar.home")
      out.write("</a></li>\r\n");
      out.write("                                <li><a href=\"admin.jsp\" ><i class=\"icon-cogs icon-large\"></i> Admin");
//=ResourceLoader.GetResource(session, "navbar.home")
      out.write("</a></li>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                                <li class=\"dropdown\"><a href=\"#\" data-toggle=\"dropdown\" class=\"dropdowb-town\"><i class=\"icon-question-sign icon-large\"></i>");
      out.print(ResourceLoader.GetResource(session, "navbar.help"));
      out.write(" <b class=\"caret\"></b></a>\r\n");
      out.write("                                    <ul class=\"dropdown-menu\">\r\n");
      out.write("                                         <li><a href=\"http://juddi.apache.org/docs.html\" title=\"");
      out.print(ResourceLoader.GetResource(session, "navbar.help.userguide"));
      out.write('"');
      out.write('>');
      out.print(ResourceLoader.GetResource(session, "navbar.help.userguide"));
      out.write("</a></li>\r\n");
      out.write("                                        <li><a href=\"http://wiki.apache.org/juddi\" title=\"");
      out.print(ResourceLoader.GetResource(session, "navbar.help.wiki"));
      out.write('"');
      out.write('>');
      out.print(ResourceLoader.GetResource(session, "navbar.help.wiki"));
      out.write("</a></li>\r\n");
      out.write("                                        <li><a href=\"http://juddi.apache.org/issue-tracking.html\" title=\"");
      out.print(ResourceLoader.GetResource(session, "navbar.help.bugreport"));
      out.write('"');
      out.write('>');
      out.print(ResourceLoader.GetResource(session, "navbar.help.bugreport"));
      out.write("</a></li>\r\n");
      out.write("                                        <li><a href=\"http://juddi.apache.org/\" title=\"");
      out.print(ResourceLoader.GetResource(session, "navbar.help.website"));
      out.write('"');
      out.write('>');
      out.print(ResourceLoader.GetResource(session, "navbar.help.website"));
      out.write("</a></li>\r\n");
      out.write("                                        <li><a href=\"http://juddi.apache.org/mailing-list.html\" title=\"");
      out.print(ResourceLoader.GetResource(session, "navbar.help.mailinglist"));
      out.write('"');
      out.write('>');
      out.print(ResourceLoader.GetResource(session, "navbar.help.mailinglist"));
      out.write("</a></li>\r\n");
      out.write("                                        <li><a href=\"http://juddi.apache.org/source.html\" title=\"");
      out.print(ResourceLoader.GetResource(session, "navbar.help.source"));
      out.write('"');
      out.write('>');
      out.print(ResourceLoader.GetResource(session, "navbar.help.source"));
      out.write("</a></li>\r\n");
      out.write("                                        <li><a href=\"about.jsp\" title=\"");
      out.print(ResourceLoader.GetResource(session, "navbar.help.about.tooltip"));
      out.write('"');
      out.write('>');
      out.print(ResourceLoader.GetResource(session, "navbar.help.about"));
      out.write("</a></li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                </li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                            <div id=\"loginfield\">\r\n");
      out.write("                                ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"navbar-form pull-right\">\r\n");
      out.write("\r\n");
      out.write("    ");

        if (session.getAttribute("username") != null && session.getAttribute("password") != null
                && ((String) session.getAttribute("username")).length() > 0 && ((String) session.getAttribute("password")).length() > 0) {
            //we're probably logged in

    
      out.write("\r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("        loggedin = true;\r\n");
      out.write("    </script>\r\n");
      out.write("    <a class=\"btn\" title=\"");
      out.print(ResourceLoader.GetResource(session, "navbar.login.logout"));
      out.write("\" href=\"javascript:logout();\">\r\n");
      out.write("        ");

                if (!request.isSecure()) {
            
      out.write("\r\n");
      out.write("            <i class=\"icon-warning-sign\" title=\"");
      out.print(ResourceLoader.GetResource(session, "warning.ssl"));
      out.write("\"></i>\r\n");
      out.write("            ");

                }
            
      out.write("\r\n");
      out.write("        \r\n");
      out.write("        <i class=\"icon-user\"></i>\r\n");
      out.write("        ");

            out.write(ResourceLoader.GetResource(session, "items.welcome") + " " + StringEscapeUtils.escapeHtml((String) session.getAttribute("username")) + "</a>");

        } else {
        
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <script type=\"text/javascript\">\r\n");
      out.write("            loggedin = false;\r\n");
      out.write("        </script>\r\n");
      out.write("\r\n");
      out.write("        <input class=\"span2\" type=\"text\" placeholder=\"");
      out.print(ResourceLoader.GetResource(session, "navbar.login.username"));
      out.write("\" name=\"username\" id=\"username\">\r\n");
      out.write("        <input class=\"span2\" type=\"password\" placeholder=\"");
      out.print(ResourceLoader.GetResource(session, "navbar.login.password"));
      out.write("\" name=\"password\" id=\"password\">\r\n");
      out.write("        <button type=\"button\" onclick=\"javascript:Login();\" class=\"btn\" id=\"loginbutton\">\r\n");
      out.write("            ");

                if (!request.isSecure() ||  !UddiAdminHub.getInstance(application, session).isSecure()) {
            
      out.write("\r\n");
      out.write("            <i class=\"icon-warning-sign\" title=\"");
      out.print(ResourceLoader.GetResource(session, "warning.ssl"));
      out.write("\"></i>\r\n");
      out.write("            ");

                }
            
      out.write("\r\n");
      out.write("            ");
      out.print(ResourceLoader.GetResource(session, "navbar.login.button"));
      out.write("\r\n");
      out.write("        </button>\r\n");
      out.write("        ");

            }
        
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("        \r\n");
      out.write("            \r\n");
      out.write("<div class=\"modal hide fade container\" id=\"loginfailure\">\r\n");
      out.write("    <div class=\"modal-header\">\r\n");
      out.write("        <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-hidden=\"true\">&times;</button>\r\n");
      out.write("        <h3>");
      out.print(ResourceLoader.GetResource(session, "errors.generic"));
      out.write("</h3>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"modal-body\">\r\n");
      out.write("            <i class=\"icon-4x icon-thumbs-down\"></i><br>\r\n");
      out.write("            <div id=\"loginfailuredetails\"></div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"modal-footer\">\r\n");
      out.write("            <button type=\"button\" class=\"btn\" data-dismiss=\"modal\" >");
      out.print(ResourceLoader.GetResource(session, "modal.close"));
      out.write("</button>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>");
      out.write("\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div><!--/.nav-collapse -->\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Main hero unit for a primary marketing message or call to action -->\r\n");
      out.write("    <div class=\"hero-unit\">\r\n");
      out.write("        <h1>");
      out.print(ResourceLoader.GetResource(session, "pages.home.title"));
      out.write("</h1>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Example row of columns -->\r\n");
      out.write("    <div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <div class=\"span4\">\r\n");
      out.write("            <h2>");
      out.print(ResourceLoader.GetResource(session, "pages.home.config"));
      out.write("</h2>\r\n");
      out.write("            <p>");
      out.print(ResourceLoader.GetResource(session, "pages.home.config"));
      out.write("</p>\r\n");
      out.write("            <p><a class=\"btn btn-primary\" href=\"configure.jsp\">");
      out.print(ResourceLoader.GetResource(session, "viewdetails"));
      out.write(" &raquo;</a></p>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"span4\">\r\n");
      out.write("            <h2>");
      out.print(ResourceLoader.GetResource(session, "pages.home.stats"));
      out.write("</h2>\r\n");
      out.write("            <p>");
      out.print(ResourceLoader.GetResource(session, "pages.home.stats.content"));
      out.write("</p>\r\n");
      out.write("            <p><a class=\"btn btn-primary\" href=\"stats.jsp\">");
      out.print(ResourceLoader.GetResource(session, "viewdetails"));
      out.write(" &raquo;</a></p>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"span4\">\r\n");
      out.write("            <h2>");
      out.print(ResourceLoader.GetResource(session, "pages.home.admin"));
      out.write("</h2>\r\n");
      out.write("            <p>");
      out.print(ResourceLoader.GetResource(session, "pages.home.admin.content"));
      out.write("Administration options, such as deleting entities.</p>\r\n");
      out.write("            <p><a class=\"btn btn-primary\" href=\"admin.jsp\">");
      out.print(ResourceLoader.GetResource(session, "viewdetails"));
      out.write(" &raquo;</a></p>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("            \r\n");
      out.write("             <div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <div class=\"span4\">\r\n");
      out.write("            <h2>");
      out.print(ResourceLoader.GetResource(session, "pages.admin.changes"));
      out.write("</h2>\r\n");
      out.write("            <p>");
      out.print(ResourceLoader.GetResource(session, "pages.admin.changes.content"));
      out.write("</p>\r\n");
      out.write("            <p><a class=\"btn btn-primary\" href=\"changes.jsp\">");
      out.print(ResourceLoader.GetResource(session, "viewdetails"));
      out.write(" &raquo;</a></p>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"span4\">\r\n");
      out.write("          \r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"span4\">\r\n");
      out.write("          \r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("            \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</div> <!-- /container -->\r\n");
      out.write("</form>\r\n");
      out.write("<div style=\"\r\n");
      out.write("     padding: 0px 0px 0px 0px; bottom: 0px; margin: 0px 0px 0px 0px; width:100%; text-align: center; position: fixed; \r\n");
      out.write("     background-color: white; \r\n");
      out.write("     \"><center><footer>v");

     out.write(StringEscapeUtils.escapeHtml(org.apache.juddi.v3.client.Release.getRegistryVersion()));
     
      out.write(" - <a href=\"http://www.apache.org\">");
      out.print(ResourceLoader.GetResource(session, "footer.apachecopyright"));
      out.write("</a></footer></center></div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
