package br.ufpe.activiti.behaviour.drools

import br.ufpe.activiti.behaviour.drools.Codigo;
import function br.ufpe.activiti.behaviour.ciclo.mapek.Executor.executarDrools;

dialect "java"
rule "Regra para adaptar"
    when
        c : Codigo( codigoParaAnalise <= Codigo.LIMITE)
    then
    	System.out.println("O código precisa adaptar!");
    	executarDrools(0);
end

rule "Regra para não adaptar"
    when
        c : Codigo( codigoParaAnalise > Codigo.LIMITE)
    then
    	System.out.println("O código não precisa adaptar!");
    	executarDrools(1);
end
